#!/usr/bin/perl -w  

use Config;

my $vendorarch = substr($Config{vendorarch}, 1);
print "debian/build/objs/src/http/modules/perl/blib/arch/auto/nginx/* $vendorarch/auto/nginx\n";
print "debian/build/objs/src/http/modules/perl/blib/lib/nginx.pm $vendorarch\n";

print "debian/conf/* etc/nginx
debian/build/objs/nginx usr/sbin
debian/conf/conf.d/*  etc/nginx/conf.d
debian/vim/nginx.yaml usr/share/vim/registry
contrib/vim/* usr/share/vim/addons\n";



